<#
.SYNOPSIS
    Pre-import tablespace capacity check — compares Production vs Stage and
    generates or applies remediation SQL before impdp runs.

.DESCRIPTION
    Runs as Phase 0 of Start-OracleImport.ps1 (or standalone).

    Steps:
      1. Query Stage tablespace usage and datafile layout live via SQL*Plus.
      2. Read the Production tablespace snapshot (TablespaceSnapshot.json)
         generated by New-TablespaceSnapshot.ps1 on the export server.
      3. Compare: flag any Stage tablespace where free space is insufficient
         to absorb the Production used data (with a configurable safety buffer).
      4. Generate ALTER DATABASE DATAFILE ... AUTOEXTEND / RESIZE SQL and,
         where needed, ALTER TABLESPACE ... ADD DATAFILE commands.
      5. If -AutoFix is specified, apply the remediation SQL on Stage.
      6. Send an HTML email report with the full comparison table and SQL.

    Exit codes: 0 = all OK (or issues fixed), 1 = issues found and not fixed.

.PARAMETER ConfigPath
    Path to ImportConfig.json.  Default: .\Config\ImportConfig.json

.PARAMETER ProdSnapshotPath
    Path to TablespaceSnapshot.json from Production.
    Default: <ImportBaseDirectory>\TablespaceSnapshot.json

.PARAMETER AutoFix
    Apply the generated remediation SQL automatically on Stage.

.PARAMETER DryRun
    Generate the comparison and SQL but do NOT apply anything.

.PARAMETER AlertThresholdPct
    Warn if a Stage tablespace is above this % utilisation.  Default: 80

.PARAMETER SafetyBufferPct
    Extra headroom added on top of Prod used space when sizing MaxMB.  Default: 20

.EXAMPLE
    .\Start-TablespacePreCheck.ps1
    .\Start-TablespacePreCheck.ps1 -AutoFix
    .\Start-TablespacePreCheck.ps1 -DryRun

.NOTES
    Compatible : PowerShell 5.0+
    Runs on    : aazeud-oracle03 (Stage)
    Requires   : TablespaceSnapshot.json copied from Prod by Start-DataTransfer.ps1
    Author     : DBA Team - Ashley Furniture India
#>
[CmdletBinding()]
param(
    [string]$ConfigPath        = "$PSScriptRoot\Config\ImportConfig.json",
    [string]$ProdSnapshotPath  = "",
    [switch]$AutoFix,
    [switch]$DryRun,
    [int]   $AlertThresholdPct = 80,
    [int]   $SafetyBufferPct   = 20
)

Set-StrictMode -Version 2.0
$ErrorActionPreference = 'Stop'

$Script:LogWriter = $null
$RunTimestamp     = Get-Date -Format 'yyyyMMdd_HHmmss'

# ─────────────────────────────────────────────────────────────────────────────
# FUNCTION: Write-Log
# ─────────────────────────────────────────────────────────────────────────────
function Write-Log {
    param([string]$Message,
          [ValidateSet('INFO','WARN','ERROR','SUCCESS')][string]$Level = 'INFO',
          [string]$Phase = 'PRECHECK')
    $ts   = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $line = "[$ts] [$Level] [$Phase] $Message"
    switch ($Level) {
        'INFO'    { Write-Host $line -ForegroundColor Cyan   }
        'WARN'    { Write-Host $line -ForegroundColor Yellow }
        'ERROR'   { Write-Host $line -ForegroundColor Red    }
        'SUCCESS' { Write-Host $line -ForegroundColor Green  }
    }
    if ($Script:LogWriter) { $Script:LogWriter.WriteLine($line); $Script:LogWriter.Flush() }
}

# ─────────────────────────────────────────────────────────────────────────────
# FUNCTION: Invoke-SqlPlus
# ─────────────────────────────────────────────────────────────────────────────
function Invoke-SqlPlus {
    param([string]$SqlBlock, [string]$SqlPlusExe)
    $tmpSql = Join-Path $env:TEMP "ts_check_$(Get-Date -Format 'yyyyMMddHHmmssff').sql"
    $tmpOut = "$tmpSql.out"
    $tmpErr = "$tmpSql.err"
    try {
        $SqlBlock | Set-Content -Path $tmpSql -Encoding ASCII
        $proc = Start-Process -FilePath $SqlPlusExe `
                              -ArgumentList "-S `"/ as sysdba`" @`"$tmpSql`"" `
                              -NoNewWindow -Wait -PassThru `
                              -RedirectStandardOutput $tmpOut `
                              -RedirectStandardError  $tmpErr
        $output = @()
        if (Test-Path $tmpOut) { $output += Get-Content $tmpOut }
        if (Test-Path $tmpErr) { $err = Get-Content $tmpErr; if ($err) { $output += $err } }
        return @{ ExitCode=$proc.ExitCode; Output=$output }
    }
    finally { Remove-Item $tmpSql,$tmpOut,$tmpErr -Force -ErrorAction SilentlyContinue }
}

# ─────────────────────────────────────────────────────────────────────────────
# FUNCTION: Send-PreCheckEmail
# ─────────────────────────────────────────────────────────────────────────────
function Send-PreCheckEmail {
    param([string]$Subject, [string]$Body, [string[]]$To,
          [string]$From, [string]$SMTPServer, [int]$SMTPPort,
          [string[]]$Attachments = @())
    $tempCopies = @()
    try {
        $params = @{ Subject=$Subject; Body=$Body; BodyAsHtml=$true; From=$From
                     To=$To; SmtpServer=$SMTPServer; Port=$SMTPPort }
        if ($Attachments.Count -gt 0) {
            $resolved = @()
            foreach ($att in $Attachments) {
                if (Test-Path $att) {
                    $tmp = Join-Path $env:TEMP ("$(Split-Path $att -Leaf)_$(Get-Date -Format 'HHmmssff').tmp")
                    Copy-Item -Path $att -Destination $tmp -Force
                    $resolved += $tmp; $tempCopies += $tmp
                }
            }
            if ($resolved.Count -gt 0) { $params['Attachments'] = $resolved }
        }
        Send-MailMessage @params
        Write-Log "Email sent: $Subject"
    }
    catch { Write-Log "Email failed (non-fatal): $_" -Level WARN }
    finally { $tempCopies | Remove-Item -Force -ErrorAction SilentlyContinue }
}


# ─────────────────────────────────────────────────────────────────────────────
# FUNCTION: Get-StageTablespaceInfo
# Queries Stage DB for tablespace summary + datafile detail.
# Returns hashtable: Tablespaces{}, Datafiles{}
# ─────────────────────────────────────────────────────────────────────────────
function Get-StageTablespaceInfo {
    param([string]$SqlPlusExe)

    $sql = @"
SET PAGESIZE 0
SET LINESIZE 2000
SET FEEDBACK OFF
SET HEADING OFF
SET VERIFY OFF
SET TRIMOUT ON
WHENEVER SQLERROR EXIT SQL.SQLCODE

SELECT 'TS|' || t.tablespace_name || '|' ||
       TO_CHAR(ROUND(t.allocated_mb,1)) || '|' ||
       TO_CHAR(ROUND(t.used_mb,1))      || '|' ||
       TO_CHAR(ROUND(t.free_mb,1))      || '|' ||
       TO_CHAR(ROUND(t.pct_used,1))     || '|' ||
       t.autoextensible                 || '|' ||
       TO_CHAR(ROUND(t.max_mb,1))
FROM (
    SELECT df.tablespace_name,
           df.alloc_mb                                      AS allocated_mb,
           df.alloc_mb - NVL(fs.free_mb,0)                 AS used_mb,
           NVL(fs.free_mb,0)                                AS free_mb,
           (df.alloc_mb - NVL(fs.free_mb,0))
             / NULLIF(df.alloc_mb,0) * 100                  AS pct_used,
           df.autoextensible,
           df.max_mb
    FROM  (SELECT tablespace_name,
                  SUM(bytes)/1048576                              AS alloc_mb,
                  MAX(autoextensible)                             AS autoextensible,
                  SUM(DECODE(maxbytes,0,bytes,maxbytes))/1048576  AS max_mb
           FROM   dba_data_files GROUP BY tablespace_name) df
    LEFT JOIN
          (SELECT tablespace_name, SUM(bytes)/1048576 AS free_mb
           FROM   dba_free_space GROUP BY tablespace_name) fs
    ON df.tablespace_name = fs.tablespace_name
) t
ORDER BY t.tablespace_name;

SELECT 'DF|' || tablespace_name || '|' || file_name || '|' ||
       TO_CHAR(ROUND(bytes/1048576,1)) || '|' ||
       autoextensible || '|' ||
       TO_CHAR(ROUND(DECODE(maxbytes,0,bytes,maxbytes)/1048576,1))
FROM   dba_data_files
ORDER  BY tablespace_name, file_id;
EXIT;
"@

    $result = Invoke-SqlPlus -SqlBlock $sql -SqlPlusExe $SqlPlusExe
    if ($result.ExitCode -ne 0) { throw "Stage tablespace query failed (exit $($result.ExitCode))" }

    $tablespaces = @{}
    $datafiles   = @{}

    foreach ($line in ($result.Output | Where-Object { $_.Trim() -ne '' })) {
        $parts = $line.Trim() -split '\|'
        if ($parts[0] -eq 'TS' -and $parts.Count -ge 8) {
            $name = $parts[1]
            $tablespaces[$name] = [PSCustomObject]@{
                Name        = $name;  AllocatedMB = [double]$parts[2]
                UsedMB      = [double]$parts[3]; FreeMB      = [double]$parts[4]
                PctUsed     = [double]$parts[5]; AutoExtend  = $parts[6]
                MaxMB       = [double]$parts[7]
            }
        }
        elseif ($parts[0] -eq 'DF' -and $parts.Count -ge 6) {
            $tsName = $parts[1]
            if (-not $datafiles.ContainsKey($tsName)) { $datafiles[$tsName] = @() }
            $datafiles[$tsName] += [PSCustomObject]@{
                FileName=$parts[2]; SizeMB=[double]$parts[3]
                AutoExtend=$parts[4]; MaxMB=[double]$parts[5]
            }
        }
    }
    return @{ Tablespaces=$tablespaces; Datafiles=$datafiles }
}

# ─────────────────────────────────────────────────────────────────────────────
# FUNCTION: New-RemediationSQL
# For each flagged tablespace: generates ALTER AUTOEXTEND / ADD DATAFILE SQL.
# ─────────────────────────────────────────────────────────────────────────────
function New-RemediationSQL {
    param([PSCustomObject]$StageTs, [object]$ProdTs, [array]$StageDatafiles, [int]$BufferPct)

    $sql    = @()
    $tsName = $StageTs.Name

    $targetMB = if ($ProdTs) {
        [math]::Ceiling($ProdTs.UsedMB * (1 + $BufferPct / 100))
    } else { [math]::Ceiling($StageTs.AllocatedMB * 1.5) }
    $targetMB = [math]::Max($targetMB, 1024)

    $sql += "-- [$tsName] Stage used: $($StageTs.UsedMB) MB | Free: $($StageTs.FreeMB) MB" +
            $(if ($ProdTs) { " | Prod used: $($ProdTs.UsedMB) MB | Target MaxMB: $targetMB" } else { " | Target MaxMB: $targetMB" })

    $currentTotalMaxMB = ($StageDatafiles | Measure-Object -Property MaxMB -Sum).Sum

    foreach ($df in $StageDatafiles) {
        if ($df.AutoExtend -eq 'NO' -or $df.MaxMB -lt $targetMB) {
            $sql += "ALTER DATABASE DATAFILE '$($df.FileName)' AUTOEXTEND ON NEXT 512M MAXSIZE ${targetMB}M;"
        }
    }

    if ($currentTotalMaxMB -lt $targetMB) {
        $shortfallMB = [math]::Ceiling($targetMB - $currentTotalMaxMB + 512)
        $baseDir     = Split-Path $StageDatafiles[0].FileName -Parent
        $newFile     = Join-Path $baseDir "$($tsName.ToLower())_ext01.dbf"
        $sql += "ALTER TABLESPACE $tsName ADD DATAFILE '$newFile' SIZE ${shortfallMB}M AUTOEXTEND ON NEXT 512M MAXSIZE UNLIMITED;"
    }
    return $sql
}


# ─────────────────────────────────────────────────────────────────────────────
# FUNCTION: Compare-Tablespaces
# Compares Stage vs Prod snapshot; returns list of flagged tablespace objects.
# Each object includes: Name, Status, StageTs, ProdTs, RemediationSQL[]
# ─────────────────────────────────────────────────────────────────────────────
function Compare-Tablespaces {
    param(
        [hashtable]$StageInfo,        # from Get-StageTablespaceInfo
        [hashtable]$ProdSnapshot,     # from JSON snapshot
        [array]    $StageDatafilesMap,# $StageInfo.Datafiles
        [int]      $AlertThresholdPct,
        [int]      $BufferPct
    )

    $results = @()

    foreach ($tsName in ($StageInfo.Tablespaces.Keys | Sort-Object)) {
        $stageTs = $StageInfo.Tablespaces[$tsName]
        $stageDf = if ($StageInfo.Datafiles.ContainsKey($tsName)) { $StageInfo.Datafiles[$tsName] } else { @() }

        # Look up Prod data — JSON deserialization gives PSCustomObject
        $prodTs = $null
        if ($ProdSnapshot.Tablespaces -and $ProdSnapshot.Tablespaces.PSObject.Properties[$tsName]) {
            $prodTs = $ProdSnapshot.Tablespaces.PSObject.Properties[$tsName].Value
        }

        $status        = 'OK'
        $remediationSql = @()
        $reason         = ''

        # Check 1: above alert threshold
        if ($stageTs.PctUsed -ge $AlertThresholdPct) {
            $status = 'WARNING'
            $reason = "Stage at $($stageTs.PctUsed)% (threshold: $AlertThresholdPct%)"
        }

        # Check 2: Stage free space < Prod used space (plus buffer)
        if ($prodTs) {
            $prodUsedMB    = [double]$prodTs.UsedMB
            $requiredMB    = [math]::Ceiling($prodUsedMB * (1 + $BufferPct / 100))
            $stageMaxMB    = $stageTs.MaxMB
            $stageTotalAvailMB = $stageMaxMB - $stageTs.UsedMB

            if ($stageTotalAvailMB -lt $requiredMB) {
                $status = 'INSUFFICIENT'
                $reason = "Stage avail: $stageTotalAvailMB MB, Prod needs: $requiredMB MB (Prod used: $prodUsedMB MB + $BufferPct% buffer)"
            }
        }

        # Check 3: AUTOEXTEND off and high usage
        if ($stageTs.AutoExtend -eq 'NO' -and $stageTs.PctUsed -ge 70) {
            if ($status -eq 'OK') { $status = 'WARNING' }
            $reason += " | AUTOEXTEND is OFF at $($stageTs.PctUsed)% usage"
        }

        if ($status -ne 'OK' -and $stageDf.Count -gt 0) {
            $remediationSql = New-RemediationSQL -StageTs $stageTs -ProdTs $prodTs `
                                                  -StageDatafiles $stageDf -BufferPct $BufferPct
        }

        $results += [PSCustomObject]@{
            Name           = $tsName
            Status         = $status
            Reason         = $reason
            StageTs        = $stageTs
            ProdTs         = $prodTs
            RemediationSQL = $remediationSql
        }
    }
    return $results
}

# ─────────────────────────────────────────────────────────────────────────────
# FUNCTION: Build-HtmlReport
# Builds the HTML email body from comparison results.
# ─────────────────────────────────────────────────────────────────────────────
function Build-HtmlReport {
    param([array]$Results, [string]$RunAt, [bool]$Fixed, [bool]$DryRun)

    $style = @"
<style>
body{font-family:Arial,sans-serif;font-size:13px;}
table{border-collapse:collapse;width:100%;}
th{background:#2c3e50;color:#fff;padding:6px 10px;text-align:left;}
td{padding:5px 10px;border:1px solid #ddd;}
tr.ok{background:#eafaf1;}tr.warning{background:#fef9e7;}
tr.insufficient{background:#fdecea;}tr.fixed{background:#eaf4fb;}
.sql{font-family:Consolas,monospace;font-size:12px;background:#f4f4f4;
     padding:8px;border-left:4px solid #2980b9;margin:4px 0;}
</style>
"@

    $rows = foreach ($r in $Results) {
        $cssClass = switch ($r.Status) {
            'OK'           { 'ok' }
            'WARNING'      { 'warning' }
            'INSUFFICIENT' { if ($Fixed) { 'fixed' } else { 'insufficient' } }
            default        { 'ok' }
        }
        $statusTxt  = if ($Fixed -and $r.Status -eq 'INSUFFICIENT') { 'FIXED' } else { $r.Status }
        $prodUsed   = if ($r.ProdTs) { "$([math]::Round([double]$r.ProdTs.UsedMB,1)) MB" } else { 'N/A' }
        $sqlHtml    = if ($r.RemediationSQL.Count -gt 0) {
            ($r.RemediationSQL | ForEach-Object { "<div class='sql'>$_</div>" }) -join ''
        } else { '' }

        "<tr class='$cssClass'><td>$($r.Name)</td><td>$statusTxt</td>" +
        "<td>$($r.StageTs.UsedMB) MB</td><td>$($r.StageTs.FreeMB) MB</td>" +
        "<td>$($r.StageTs.MaxMB) MB</td><td>$prodUsed</td>" +
        "<td>$($r.Reason)</td></tr>" +
        $(if ($sqlHtml) { "<tr class='$cssClass'><td colspan='7'>$sqlHtml</td></tr>" } else { '' })
    }

    $dryNote = if ($DryRun) { '<p><b>DRY RUN - no changes were applied.</b></p>' } else { '' }
    $fixNote = if ($Fixed)  { "<p style='color:green;'><b>Remediation SQL was applied automatically.</b></p>" } else { '' }

    return @"
<!DOCTYPE html><html><head>$style</head><body>
<h2>Tablespace Pre-Check Report</h2>
<p>Run at: $RunAt | Server: $($env:COMPUTERNAME)</p>
$dryNote$fixNote
<table>
<tr><th>Tablespace</th><th>Status</th><th>Stage Used</th><th>Stage Free</th>
    <th>Stage Max</th><th>Prod Used</th><th>Reason / Notes</th></tr>
$($rows -join '')
</table></body></html>
"@
}


# ─────────────────────────────────────────────────────────────────────────────
# MAIN EXECUTION
# ─────────────────────────────────────────────────────────────────────────────
$exitCode = 0

try {
    # ── Load config ──────────────────────────────────────────────────────────
    if (-not (Test-Path $ConfigPath)) { throw "Config not found: $ConfigPath" }
    $config      = Get-Content -Path $ConfigPath -Raw | ConvertFrom-Json
    $sqlplusExe  = Join-Path $config.OracleHome 'bin\sqlplus.exe'
    $logDir      = $config.LogDirectory
    $importBase  = $config.ImportBaseDirectory

    if (-not (Test-Path $logDir)) { New-Item -ItemType Directory -Path $logDir -Force | Out-Null }

    $logPath = Join-Path $logDir "TablespacePreCheck_$RunTimestamp.log"
    $Script:LogWriter = New-Object System.IO.StreamWriter(
        $logPath,
        $false,
        [System.Text.Encoding]::UTF8,
        4096
    )
    $Script:LogWriter.AutoFlush = $true

    Write-Log "=== Tablespace Pre-Check START ===" -Level INFO
    Write-Log "Config  : $ConfigPath"
    Write-Log "Log     : $logPath"
    Write-Log "AutoFix : $AutoFix  | DryRun: $DryRun  | Alert: $AlertThresholdPct%  | Buffer: $SafetyBufferPct%"

    # ── Resolve Production snapshot path ─────────────────────────────────────
    if ($ProdSnapshotPath -eq '') {
        $ProdSnapshotPath = Join-Path $importBase 'TablespaceSnapshot.json'
    }
    if (-not (Test-Path $ProdSnapshotPath)) {
        Write-Log "Production snapshot not found at: $ProdSnapshotPath" -Level WARN
        Write-Log "Proceeding with Stage-only checks (no Prod comparison)." -Level WARN
        $prodSnapshot = $null
    }
    else {
        Write-Log "Loading Production snapshot: $ProdSnapshotPath"
        $prodSnapshot = Get-Content -Path $ProdSnapshotPath -Raw | ConvertFrom-Json
        Write-Log "Snapshot captured at: $($prodSnapshot.CapturedAt) on $($prodSnapshot.Server)"
    }

    # ── Query Stage tablespace info ───────────────────────────────────────────
    Write-Log "Querying Stage tablespace info via SQL*Plus..."
    $stageInfo = Get-StageTablespaceInfo -SqlPlusExe $sqlplusExe
    Write-Log "Stage tablespaces found: $($stageInfo.Tablespaces.Count)" -Level SUCCESS

    # ── Compare ───────────────────────────────────────────────────────────────
    $emptyProdSnap = if ($prodSnapshot) { $prodSnapshot } else { @{ Tablespaces = $null } }
    $compareResults = Compare-Tablespaces `
        -StageInfo          $stageInfo `
        -ProdSnapshot       $emptyProdSnap `
        -StageDatafilesMap  $stageInfo.Datafiles `
        -AlertThresholdPct  $AlertThresholdPct `
        -BufferPct          $SafetyBufferPct

    $okCount          = ($compareResults | Where-Object { $_.Status -eq 'OK' }).Count
    $warnCount        = ($compareResults | Where-Object { $_.Status -eq 'WARNING' }).Count
    $insufficientList = @($compareResults | Where-Object { $_.Status -eq 'INSUFFICIENT' })

    Write-Log "Results: $okCount OK | $warnCount WARNING | $($insufficientList.Count) INSUFFICIENT"

    foreach ($r in $compareResults | Where-Object { $_.Status -ne 'OK' }) {
        Write-Log "[$($r.Status)] $($r.Name) - $($r.Reason)" -Level $(if ($r.Status -eq 'INSUFFICIENT') { 'ERROR' } else { 'WARN' })
    }

    # ── Apply remediation if AutoFix and not DryRun ───────────────────────────
    $fixed = $false
    if ($insufficientList.Count -gt 0 -and $AutoFix -and -not $DryRun) {
        Write-Log "Applying remediation SQL for $($insufficientList.Count) tablespace(s)..." -Level WARN
        $allSql  = @("SET ECHO ON", "WHENEVER SQLERROR CONTINUE")
        foreach ($r in $insufficientList) {
            $allSql += $r.RemediationSQL
        }
        $allSql += "EXIT;"

        $fixResult = Invoke-SqlPlus -SqlBlock ($allSql -join "`n") -SqlPlusExe $sqlplusExe
        foreach ($line in $fixResult.Output) { Write-Log $line }

        if ($fixResult.ExitCode -ne 0) {
            Write-Log "Remediation completed with warnings (exit $($fixResult.ExitCode))" -Level WARN
        }
        else {
            Write-Log "Remediation applied successfully." -Level SUCCESS
            $fixed = $true
        }
    }
    elseif ($insufficientList.Count -gt 0 -and -not $AutoFix) {
        Write-Log "INSUFFICIENT tablespaces detected. Run with -AutoFix to apply remediation." -Level WARN
        foreach ($r in $insufficientList) {
            Write-Log "  Remediation SQL for $($r.Name):" -Level WARN
            foreach ($s in $r.RemediationSQL) { Write-Log "    $s" -Level WARN }
        }
        $exitCode = 1
    }

    # ── Send email report ─────────────────────────────────────────────────────
    $runAt      = Get-Date -Format 'yyyy-MM-dd HH:mm:ss'
    $htmlBody   = Build-HtmlReport -Results $compareResults -RunAt $runAt -Fixed $fixed -DryRun $DryRun.IsPresent
    $statusWord = if ($insufficientList.Count -eq 0) { 'OK' } elseif ($fixed) { 'FIXED' } else { 'ACTION REQUIRED' }
    $subject    = "[$statusWord] Stage Tablespace Pre-Check | $($env:COMPUTERNAME) | $runAt"

    Send-PreCheckEmail `
        -Subject    $subject `
        -Body       $htmlBody `
        -To         $config.Email.DBARecipients `
        -From       $config.Email.From `
        -SMTPServer $config.Email.SMTPServer `
        -SMTPPort   $config.Email.SMTPPort `
        -Attachments @($logPath)

    Write-Log "=== Tablespace Pre-Check COMPLETE === Exit: $exitCode" -Level $(if ($exitCode -eq 0) { 'SUCCESS' } else { 'WARN' })
}
catch {
    Write-Log "FATAL: $_" -Level ERROR
    $exitCode = 1
}
finally {
    if ($Script:LogWriter) {
        $Script:LogWriter.Flush()
        $Script:LogWriter.Close()
        $Script:LogWriter.Dispose()
    }
}

exit $exitCode
